server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    # Single-page app: serving index.html for all routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caching hashed assets forever (Reduces build time, eve though not significant in this case, best practices)
    location ~* \.(js|css|woff2?|ttf|eot|svg|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
}
